### ISSUE TITLE
Call to member function getType() on null

### ISSUE THREAD

**Issue by dylanjacob** [partkeepr/PartKeepr#579] opened 2016-01-25 17:49 UTC
I have had this error pop up multiple times doing multiple activities, but in particular I see this issue when trying to add parts to a project. I added some (say 7 for the sake of example) parts and saved the project, but when I try to add additional parts and save the changes to the project I receive an error "Call to member function getType() on null".

Looking at the details, it looks like a request to `PUT /api/projects/1?_dc=1453743452067` results in a 500 response.

Related apache2 logs:
```
[Mon Jan 25 09:44:47.181971 2016] [:error] [pid 33018] [client <ip redacted>:59881] PHP Notice:  Undefined offset: 0 in /var/www/PartKeepr/vendor/dunglas/api-bundle/JsonLd/Serializer/ItemNormalizer.php on line 241, referer: https://<hostname redacted>/
[Mon Jan 25 09:44:47.182221 2016] [:error] [pid 33018] [client <ip redacted>:59881] PHP Fatal error:  Call to a member function getType() on null in /var/www/PartKeepr/vendor/dunglas/api-bundle/JsonLd/Serializer/ItemNormalizer.php on line 241, referer: https://<hostname redacted>/
```
It looks like the issue is related to a dependency (github: dunglas/DunglasApiBundle).  From what I can tell there are no open bugs with that project that sound similar, so this may be better suited for that project, but I wanted to post here as well to see if anyone had any ideas.

**Comment by felicitus** [comment] 2016-01-25 19:18
Can you reproduce the issue on demo.partkeepr.org ?

**Comment by dylanjacob** [comment] 2016-01-25 20:31
Yes.  When I create a project, add some parts and save the project, then add some more parts (even just 1) and attempt to save again I get the error.

![screen shot 2016-01-25 at 12 30 54 pm](https://cloud.githubusercontent.com/assets/1731901/12563523/886695f8-c35f-11e5-9eb7-0663bac52e33.png)

**Comment by dylanjacob** [comment] 2016-01-27 19:59
This looks like a issue with the dunglas/api-bundle package.  Will create issue and potential PR with that project.

**Comment by felicitus** [comment] 2016-01-27 20:03
I'd like to keep this issue open for tracking if that's OK with you.

**Comment by dylanjacob** [comment] 2016-01-27 20:04
That's fine, I'll reopen.

**Comment by vmw** [comment] 2016-01-27 20:16
I can confirm this issue; as it happens - and I just found this issue by googling the ItemNormalizer file.

My partskeeper log file shows;

[2016-01-27 19:55:10] php.CRITICAL: Fatal Error: Call to a member function getType() on null {"type":1,"file":"/home/parts/vendor/dunglas/api-bundle/JsonLd/Serializer/ItemNormalizer.php","line":241,"level":6143,"stack":[]} []

Also of note might be this conversation of the issue;
https://www.bountysource.com/issues/25457381-type-not-getting-inheritdoc-data

Any workarounds would be greatly appreciated; I'm trying to troubleshoot the issue now, as we're trying to add new files to the project.

**Comment by dylanjacob** [comment] 2016-01-27 20:20
I'm playing with updating line 229 to something like
```
if ('@' === $attributeName[0] || is_null($attributeName[0])) {
    continue;
}
```

This seems to work cleanly, at least for this application.

**Comment by dylanjacob** [comment] 2016-01-27 21:04
I've submitted a pull request to dunglas/DunglasApiBundle with the previously described change.  Hopefully it will get it merged soon.

**Comment by vmw** [comment] 2016-01-28 16:22
I can confirm that your modification works. In the event it's not accepted upstream, I suggest we patch the version shipped with Partskeepr with the above modification.

**Comment by dylanjacob** [comment] 2016-01-28 16:29
So, what I'm seeing is that when a project is saved, the HTTP request is sending something like this JSON:
```
{
...
parts: {
    0: {
        ...
        project: {
            0: "/"
        },
        ....
    },
    ...
}
```
It seems that `0: "/"` is where the error happens.  All of the other parameters before the first part get processed without any problem, but as soon as the denormalize function hits this key, it reads the attribute name as null.

**Comment by vmw** [comment] 2016-01-28 16:32
How does partskeepr interpret that string? If it's interpreting the slash as an escape sequence, perhaps that would explain the error?

**Comment by felicitus** [comment] 2016-01-28 16:35
Well the serialized JSON is simply plain wrong at this point. This looks suspiciously like https://github.com/dunglas/DunglasApiBundle/issues/285

**Comment by dylanjacob** [comment] 2016-01-28 17:04
@vmw That might work if you download the zip/tarball, but for those using the git method it will not work since the dunglas/DunglasApiBundle package is a managed dependency and it is installed directly from the dunglas/DunglasApiBundle git repo when a user runs `composer install`.  The only real solution is to get it fixed at it's source.

**Comment by felicitus** [comment] 2016-01-28 17:05
No worries, we'll find a solution. Dunglas is pretty nice. I will see if I can find the root cause of the issue this weekend, sorry I can't make it earlier.

**Comment by dylanjacob** [comment] 2016-01-28 17:09
I've been digging around as well trying to 1) learn more about the PartKeepr codebase and 2) figure out what is really happening behind the scenes.

Thanks for looking into this.

**Comment by felicitus** [comment] 2016-01-28 17:15
You're welcome. If you have any more insights that would be helpful. 

One thing you could try is to return an empty array in Parts.php method getProjects(), maybe that's the problem.

**Comment by fulcrum3d** [comment] 2016-02-08 01:00
Any new progress, Felicitus?

**Comment by felicitus** [comment] 2016-02-08 03:10
@fulcrum3d not yet, the security release from yesterday had the highest priority.

**Comment by vmw** [comment] 2016-02-18 16:32
To follow up:

In addition to dylanjacob patch, we are encountering similar issues: 

2016/02/18 08:26:47 [error] 32469#0: *38536 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to a member function getName() on null in /REDACTED/src/PartKeepr/PartBundle/Entity/Part.php on line 816" while reading response header from upstream, client: REDACTED, server: REDACTED, request: "GET /api/parts?_dc=1455812807078&page=1&start=0&itemsPerPage=50&group=%7B%22property%22%3A%22categoryPath%22%2C%22direction%22%3A%22ASC%22%7D&order=%5B%7B%22property%22%3A%22category.categoryPath%22%2C%22direction%22%3A%22ASC%22%7D%2C%7B%22property%22%3A%22name%22%2C%22direction%22%3A%22ASC%22%7D%5D HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "REDACTED", referrer: "REDACTED"


This issue was addressed in a manner similar to the previous one:

I modified line 816 in /src/PartKeepr/PartBundle/Entity/Part.php;

816c816,818
<             $projectNames[] = $projectPart->getProject()->getName();
---
> 		if ( $projectPart->getProject() !== null) {
>         	    $projectNames[] = $projectPart->getProject()->getName();
> 		}


This seems to overcome subsequent errors in that form.

**Comment by felicitus** [comment] 2016-02-23 16:03
The root cause for this issue is that the ExtJS Hydra/JSON-LD deserializer does currently not support IRIs.

The backend sends an IRI, example:
```json
{
    "project": "/~felicitus/PartKeepr/web/app_dev.php/api/projects/12",
    "quantity": 4,
    "remarks": ""
}
``` 

The relation for "project" would be an object, not a string. As such, invalid data is stored and returned in an invalid manner when sending back to the backend.

This is not an issue with `DunglasApiBundle`.

**Comment by felicitus** [comment] 2016-02-29 20:46
I have to apologize for not having a bugfix yet; the underlying issue is more complex than I have anticipated. I hope to provide a bugfix in the next few weeks, but it heavily depends on my workload.

**Closed** 2016-03-08 15:16 UTC
Labels: Bug

**Comment by DTFUHF** [comment] 2016-03-25 22:04
I'm having this issue even in v1.0.0-alpha.1, please let me know if there's any info I can provide to you.

**Comment by felicitus** [comment] 2016-03-25 22:14
@DTFUHF first make sure that the issue is actually the same, and not only the same error message. Then please open a new issue with exact error details and preferably steps to reproduce on demo.partkeepr.org
