### ISSUE TITLE
Unable to change price on components

### ISSUE THREAD

**Issue by slivengood1** [partkeepr/PartKeepr#606] opened 2016-03-02 12:13 UTC
I am signed up and using the hosted service.

When I add parts I must be doing something wrong, as I check the PER ITEM check box yet the software computes the average price anyway. It always divides the price by the number entered no mater what the check box is.
I have many parts entered into the system and I can find no way to edit the price. Am I doing something wrong?

Also the currency symbol reverts back to E from $ every time I log back in.

**Comment by felicitus** [comment] 2016-03-02 12:45
First of all, please create a separate issue per problem, as described in [CONTRIBUTING.md](https://github.com/partkeepr/PartKeepr/blob/master/CONTRIBUTING.md)

This issue is a duplicate of #593 and #302

**Closed by felicitus** 2016-03-02 12:45 UTC

**Comment by slivengood1** [comment] 2016-03-02 13:03
How do I update the price of components. I have many that are wrong. There is no way I can find to edit the price field when I try to edit the part. I do not care the least little bit about average prices.

**Comment by felicitus** [comment] 2016-03-02 13:04
You can't. The displayed price is an average price which is always calculated. As I've mentioned above, this is a duplicate of issue #302.

**Comment by felicitus** [comment] 2016-03-02 13:06
I'll try to prioritize the price calculation issue but I can't make any promises yet.

**Comment by slivengood1** [comment] 2016-03-02 13:17
OK, I thought I was missing something on getting to the field.

**Comment by felicitus** [comment] 2016-03-02 13:19
No, it's unfortunately a bug in PartKeepr itself. The average price is only an "aid" in finding out how much your stock is worth.
