### ISSUE TITLE
display blank page on Centos7 after installation

### ISSUE THREAD

**Issue by gaobo07** [partkeepr/PartKeepr#687] opened 2016-07-13 03:30 UTC
Hi,

My system is configured with Centos7, PHP7.0 and nginx.
I can go through the installation of partkeepr1.0, but after I push the submit button the explorer returns a blank page.
below is the source of the blank page

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
        "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>PartKeepr</title>

    <base href=""/>

    <link href="https://fonts.googleapis.com/css?family=Ubuntu:400,700italic"
          rel="stylesheet" type="text/css">

    <!-- Include the ExtJS CSS Theme -->
        <link rel="stylesheet" href="/css/dec566c.css"/>
    
        <link rel="icon" href="/images/245ec67.ico"/>
    
    <script type="javascript">
        var Ext = Ext || {};
        Ext.manifest = { // the same content as "app.json"
            compatibility: {
                ext: '4.2'
            }
        }
    </script>
                    <script type="text/javascript" src="/js/compiled/extjs.js"></script>
        
            <script type="text/javascript" src="/js/compiled/main.js"></script>
            <script type="text/javascript" src="/js/compiled/models.js"></script>
    
        <script type="text/javascript" src="/js/compiled/main2.js"></script>
    </head>
<body>
<div id="loading"><span class="logo"></span></div>
<script type="text/javascript">
    window.parameters = {"doctrine_orm_version":"2.5.4","doctrine_dbal_version":"2.5.2","doctrine_common_version":"2.6.0-DEV","php_version":"7.0.6","auto_start_session":true,"maxUploadSize":2097152,"availableImageFormats":["JPG","GIF","PNG"],"max_users":"unlimited","authentication_provider":"PartKeepr.Auth.HTTPBasicAuthenticationProvider","tip_of_the_day_uri":"https:\/\/partkeepr.org\/tips\/%s","password_change":true};
</script>
</body>
</html>

```

Can anyone help this?

BR,
David

**Comment by felicitus** [comment] 2016-07-13 08:43
Check if you get any javascript errors in your browser's JS console (typically F12)

**Comment by gaobo07** [comment] 2016-07-14 01:16
My brower is google chrome, version 51.0.2704.103 m, I got error
```
extjs.js:22 GET http://www.google.com/jsapi?_dc=1468458346918 net::ERR_CONNECTION_RESETevaluateLoadElement @ extjs.js:22loadCrossDomain @ extjs.js:22load @ extjs.js:22loadEntries @ extjs.js:22processRequest @ extjs.js:22load @ extjs.js:22loadScripts @ extjs.js:22b.onCreated @ extjs.js:22g.onCreated @ extjs.js:22onBeforeCreated @ extjs.js:22doProcess @ extjs.js:22(anonymous function) @ extjs.js:22load @ extjs.js:22require @ extjs.js:22(anonymous function) @ extjs.js:22(anonymous function) @ extjs.js:22doProcess @ extjs.js:22process @ extjs.js:22d @ extjs.js:22create @ extjs.js:22define @ extjs.js:22(anonymous function) @ extjs.js:23
content.scripts.c.js:11 TableManager::findTables()
```

**Comment by gaobo07** [comment] 2016-07-15 05:08
problem is solved. that's caused by nginx configuration.
I can go to login by just uncommenting the below lines in default.conf
```
    # Deny .ht* access
    #location ~ /\.ht {
    #    deny all;
    #}
```

**Comment by felicitus** [comment] 2016-07-18 17:02
Is the installation reachable over the internet, so I can have a look?

**Comment by gaobo07** [comment] 2016-07-18 22:59
yes, I can install a teamviewer or your preferable way,  when are you available?

**Comment by felicitus** [comment] 2016-07-18 23:09
I meant if the URL of your PartKeepr installation is reachable over the internet

**Comment by felicitus** [comment] 2016-07-18 23:11
It seems that the culprit is the connection reset to google.com/jsapi, I believe that's the issue you need to fix

**Comment by gaobo07** [comment] 2016-07-19 01:34
![image](https://cloud.githubusercontent.com/assets/11581728/16935662/df181ac0-4d93-11e6-8155-7f48f95bb7d6.png)

do you mean the above infomation?

**Comment by gaobo07** [comment] 2016-07-19 02:14
![image](https://cloud.githubusercontent.com/assets/11581728/16936473/8ae46f2a-4d99-11e6-9302-8583cc1e753e.png)

**Comment by gaobo07** [comment] 2016-07-19 02:15
![image](https://cloud.githubusercontent.com/assets/11581728/16936485/9fc7dde6-4d99-11e6-9317-d7c85c16d2f2.png)
database configuration has a warning

**Comment by gaobo07** [comment] 2016-07-19 02:20
![image](https://cloud.githubusercontent.com/assets/11581728/16936564/3ad7e6aa-4d9a-11e6-9ce6-3fafdf9cbf21.png)
some time pops up an error of warming up the cache.

**Comment by gaobo07** [comment] 2016-07-19 02:22
Re-run setup, cache successfully warmed up
![image](https://cloud.githubusercontent.com/assets/11581728/16936626/b3d0a0e2-4d9a-11e6-87e5-73e83fc69696.png)

**Comment by gaobo07** [comment] 2016-07-19 02:24
then submit got the blank page.
![image](https://cloud.githubusercontent.com/assets/11581728/16936659/f741bb40-4d9a-11e6-9ecd-c42e252e9b42.png)

**Comment by felicitus** [comment] 2016-07-19 09:30
Your problem is `GET http://www.google.com/jsapi?_dc=1468458346918 net::ERR_CONNECTION_RESET       extjs.js:22 ` which you need to fix. It seems that your network is broken.

You could try to open https://demo.partkeepr.org from the exact same browser and see if the same happens as well.

**Comment by gaobo07** [comment] 2016-07-19 09:44
I can open the website, and I downloaded the partkeepr vitual machine, I can open it too.

**Comment by felicitus** [comment] 2016-07-19 12:08
I'm talking about https://demo.partkeepr.org - the demo site, not the regular web site. Can you go there and see if the demo system works for you?

**Comment by gaobo07** [comment] 2016-07-19 23:00
Thanks felicitus, you are right, it's the network problem. now I can open the website. Apache 2.4 is tested ,and website is working too.
Could you explain why does v0.1.9 virtual machine image can work in my local network. but the 1.0.0 version need internet request? Is it possible to put the internet request file to virtual machine?

**Comment by gaobo07** [comment] 2016-07-20 02:54
Below link talked about the connection problem. which suggests to rebuild the ux package without the things that require google APIs
https://www.sencha.com/forum/showthread.php?304968-Application-hangs-when-trying-to-load-google-jsapi-without-internet-connection.

**Comment by felicitus** [comment] 2016-08-02 14:19
I believe the issue is now fixed as we're now only including the Ext.ux files we need instead of including all. Please test it with the upcoming version and re-open if necessary

**Closed by felicitus** 2016-08-02 14:19 UTC
