### ISSUE TITLE
footprints attachment issue

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#820] opened 2017-02-16 14:05 UTC
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)

# System Information

* PartKeepr Version:1.2.0
* Reproducible on the demo system: Yes
* [JavaScript errors](http://wiki.partkeepr.org/wiki/Issues/Opening_the_JavaScript_Console): 

Please attach files, for example, screenshots to describe your issue. If you can, create a screenshot ob View->System Information.

# How to reproduce
edit---footprint----attachment file-- 
An error occurred

Details
==================================
Type error: Argument 1 passed to PartKeepr\FootprintBundle\Entity\Footprint::removeAttachment() must be an instance of PartKeepr\FootprintBundle\Entity\FootprintAttachment, instance of Proxies\__CG__\PartKeepr\UploadedFileBundle\Entity\TempUploadedFile given, called in /home/demo.partkeepr.org/PartKeepr/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php on line 616

Request
==================================
PUT /api/footprints/43?_dc=1487253586858

[object Object]

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Type error: Argument 1 passed to PartKeepr\\FootprintBundle\\Entity\\Footprint::removeAttachment() must be an instance of PartKeepr\\FootprintBundle\\Entity\\FootprintAttachment, instance of Proxies\\__CG__\\PartKeepr\\UploadedFileBundle\\Entity\\TempUploadedFile given, called in \/home\/demo.partkeepr.org\/PartKeepr\/vendor\/symfony\/symfony\/src\/Symfony\/Component\/PropertyAccess\/PropertyAccessor.php on line 616"}

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.14-2
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: true
availableImageFormats: JPG,GIF,PNG
autoLoginUsername: admin
autoLoginPassword: admin
motd: <p><b>Welcome to the PartKeepr demo site</b></p>
<p>
Notes:
<ul>
<li>This PartKeepr installation is rebuilt from the GIT sources at every full hour</li>
<li>Rebuild takes about one minute, and you'll receive errors during rebuild</li>
<li>The database is synced from Felicitus' personal database, which might contain german part names or other odd stuff</li>
</ul>
</p>
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

**Comment by felicitus** [comment] 2017-02-16 14:07
Duplicate of #815

**Closed by felicitus** 2017-02-16 14:07 UTC
