### ISSUE TITLE
Custom fields per category

### ISSUE THREAD

**Issue by DIYsciBorg** [partkeepr/PartKeepr#414] opened 2015-07-22 10:52 UTC
Feature request
Several other feature requests seem to lean on additional fields. For example serial numbers, drawers in a cabinet, etc.
The status and condition fields seem not used much (at least not at all by me..maybe I am missing some really great feature?) and could be reused case by case (along with description fields) to accomplish all of this.. but the ability to add own fields would be REALLY nice.
I think at the category level is about as granular as one would need to go with this.
Perhaps the ability to "lock" quantity at 1 and hide it for items that have serial numbers?

**Comment by felicitus** [comment] 2015-07-22 11:41
This is most likely a duplicate of #400

**Comment by DIYsciBorg** [comment] 2015-07-26 16:23
yep. sorry. I swear I searched for it. apparently not thoroughly. Its not even that far back.  I am the FAIL

**Comment by felicitus** [comment] 2015-07-26 19:24
No worries :) I will close this as duplicate.

**Closed by felicitus** 2015-07-26 19:24 UTC
Labels: Feature Request
