### ISSUE TITLE
Column selection and width not saved/remembered (+ sorting columns)

### ISSUE THREAD

**Issue by MrTinkerman** [partkeepr/PartKeepr#555] opened 2016-01-10 18:14 UTC
Hi, 

A bug / feature request from MrExplore here, posting on another account.

Selecting columns and setting the width is a nice feature of partkeepr.
The selection and width are however not remembered when disconnecting.

I tested with firefox, chrome and IE.

It would be nice if column setting would be remembered.

Thanks.

**Comment by felicitus** [comment] 2016-01-10 18:16
Duplicate of #373

**Closed by felicitus** 2016-01-10 18:16 UTC
