### ISSUE TITLE
non-existent parameter "kernel.secret" with latest Symfony revision

### ISSUE THREAD

**Issue by vogelfreiheit** [partkeepr/PartKeepr#1008] opened 2018-10-21 20:38 UTC
# System Information

* PartKeepr Version: Git

I just updated to the latest codebase... while re-running setup this comes up:

` Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: The service "uri_signer" has a dependency on a non-existent parameter "kernel.secret". Did you mean this: "kernel.charset"? in /srv/webstore/www/partkeepr/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php on line ...`

I updated /vendor/* via composer properly... it seems like PartKeepr is not compatible with the latest release of Symfony.

**Comment by mindsolve** [comment] 2018-11-06 21:19
Well, AFAIK this has nothing to do with a newer Symphony version.
This error is caused by a missing or empty kernel.secret configuration,
but this value is set in /app/config/parameters.php.dist or /app/config/parameters.php
Something in your update process must have removed your configuration files.

https://stackoverflow.com/questions/20563211/the-service-uri-signer-has-a-dependency-on-a-non-existent-parameter-kernel-se/24562705

**Comment by christianlupus** [comment] 2020-01-15 13:58
@vogelfreiheit Did you update to the latest Symphony 2 release or to a new major release (aka Symphony 3 or 4)?

**Comment by baradhili** [comment] 2020-01-28 04:03
closing this as its old, it looks like a user error and it looks resolved

**Closed by baradhili** 2020-01-28 04:03 UTC
Labels: Feedback Needed
