### ISSUE TITLE
Saving newly entered part is not possible after error in parameter entry

### ISSUE THREAD

**Issue by elsni** [partkeepr/PartKeepr#224] opened 2012-06-18 15:28 UTC
When I make a mistake in the parameters entry, i.e. forget the value, an error occurs, which is correct. But even when I delete the faulty parameter line, the save button stays inactive (grey) and I cannot save the part. 

btw. I find the parameter entry not very user-friendly. A better approach would IMHO be to enter the parameter name and the value only. Value could be parsed intelligently for i.e.: 2K2, 1R, 4.5nF etc. to store value (as float)  and unit in only two columns. For display, the multiplier can be chosen automatically so that an entry of 1000R automatically becomes to 1KΩ, and 0.068uF becomes 68nF. 
##

**Comment by felicitus** [comment] 2017-06-01 20:07
I believe the issue is now gone as the part parameters have received a major rewrite. As such, I'll close the issue. If the issue still occurs, please re-open the issue. If another issue occurs, please open a new issue.

**Closed by felicitus** 2017-06-01 20:07 UTC
Labels: Bug
