### ISSUE TITLE
Search in Comment field.

### ISSUE THREAD

**Issue by agardim** [partkeepr/PartKeepr#691] opened 2016-07-20 14:01 UTC
Hi!
In later versions we are able to search inside Comment field. It was very usefull because we write compatible parts inside this field. So when we search a part we could also see compatible parts.
Now the search don't look inside this field anymore so we can't find compatible parts.
If there is some fix for this we would be very glad.
Regards!

**Comment by felicitus** [comment] 2016-07-30 12:08
Duplicate of #501

**Closed by felicitus** 2016-07-30 12:08 UTC
