### ISSUE TITLE
Printing Missing From v1.0 Alpha

### ISSUE THREAD

**Issue by ely-az** [partkeepr/PartKeepr#639] opened 2016-04-13 16:33 UTC
After upgrading to the 1.0 alpha release there is no longer any printing options. The menu items do not even appear under View. Is this intentional or did I break something?

**Comment by felicitus** [comment] 2016-04-13 16:34
Duplicate of #622

**Comment by felicitus** [comment] 2016-04-13 16:35
Yes, it was intentionally removed, refer to issue #622 for further details

**Closed by felicitus** 2016-04-13 16:34 UTC
