### ISSUE TITLE
Add/Remove Distributor Button Label doesn't fit on Button

### ISSUE THREAD

**Issue by diodenschein** [partkeepr/PartKeepr#470] opened 2015-11-05 09:23 UTC
Add Part -> Distributors

Labels on Add and Remove Buttons doesn't fit on the Buttons.

**Comment by felicitus** [comment] 2015-11-05 12:09
Looks okay at my machine:

![untitled](https://cloud.githubusercontent.com/assets/162974/10967941/6dc0c4d4-83be-11e5-9b33-e5f172a4b403.png)

Can you post a screenshot?

**Comment by diodenschein** [comment] 2015-11-05 12:18
![distributor](https://cloud.githubusercontent.com/assets/1050465/10968164/a4ee775c-83bf-11e5-9aae-43267ed8101e.jpg)

**Comment by felicitus** [comment] 2015-11-05 16:42
Do you have special DPI settings on your monitor?

**Comment by diodenschein** [comment] 2015-11-06 00:09
It's an issue with Safari (9.0.2) on OSX 10.11.2. Chrome is fine.

**Comment by felicitus** [comment] 2015-11-06 00:12
Do you know which DPI settings OSX uses? I remember a similar issue, but couldn't find it.

**Comment by diodenschein** [comment] 2015-11-06 00:27
I normally use  2560-by-1600 native resolution at 227 pixels per inch.

But even if I set it to 96Dpi PartKeepr looks the same just with less space.

**Comment by felicitus** [comment] 2015-11-08 15:42
I will try to install osx in a virtual Maschine in order to attempt to reproduce the issue.

**Comment by felicitus** [comment] 2015-11-14 14:37
Maybe the browser is set to a different zoom level? When I zoom in, it looks similar to your browser:

![untitled](https://cloud.githubusercontent.com/assets/162974/11164051/91fa6f98-8ae5-11e5-842a-a92af3a429e1.png)

**Comment by diodenschein** [comment] 2015-11-15 18:39
![sencha](https://cloud.githubusercontent.com/assets/1050465/11170305/6e1c2526-8bd0-11e5-8eb0-3046f53dedc5.jpg)

OSX: 10.11.2 Beta (15C40a)
Safari Version 9.0.2 (11601.3.9)

**Comment by backstube** [comment] 2016-07-19 21:48
There are some more places where button designators are being truncated on the right, even if there's plenty of space:

![snap1](https://cloud.githubusercontent.com/assets/5227989/16967793/3124e9fc-4e0b-11e6-813d-ca7ee9d5a4eb.png)
![snap2](https://cloud.githubusercontent.com/assets/5227989/16967802/388c98c0-4e0b-11e6-91f0-c224e0415221.png)

**Comment by felicitus** [comment] 2016-07-19 23:07
@backstube does this happen on Safari as well?

**Comment by backstube** [comment] 2016-07-19 23:18
yes, Safari 9.1.1
Sorry I forgot to mention that.

**Comment by felicitus** [comment] 2017-01-22 10:26
Sorry for the late reply - does this happen on the latest demo version as well? ExtJS was updated, so maybe the issue is now fixed?

**Comment by felicitus** [comment] 2017-01-22 10:26
Additionally, can you check if it happens with the other themes as well?

**Closed** 2020-01-18 02:44 UTC
Labels: Bug, Design, Feedback Needed
