### ISSUE TITLE
Several storage location for the same component

### ISSUE THREAD

**Issue by agamez** [partkeepr/PartKeepr#552] opened 2016-01-07 11:25 UTC
It'd be nice to be able to place the same component on different locations. Sometimes there's a laboratory storage on which a few units are available for engineers while a bigger storage has most of the components of the same type, so it'd be good that Partkeepr supports this workflow.

**Comment by felicitus** [comment] 2016-01-07 11:47
Duplicate of #90

**Closed by felicitus** 2016-01-07 11:47 UTC
