### ISSUE TITLE
Uploading attachments litters /tmp with temporary files

### ISSUE THREAD

**Issue by matthijskooijman** [partkeepr/PartKeepr#360] opened 2014-01-24 11:03 UTC
It seems that when uploading an attachment, it gets saved to /tmp during the process, but the file is then not removed from there. After uploading a bunch of attachments, my /tmp filled up with files named like "PARTKEEPR1mtqFj".

Are those supposed to be cleaned (in which case I should look more closely at my system's setup), or is this an oversight in the code?
##

**Comment by felicitus** [comment] 2017-01-31 15:17
It seems that the issue is solved as Symfony2 seems to take care of removing temporary files. At least I can't reproduce it anymore - closing.

**Closed by felicitus** 2017-01-31 15:17 UTC
Labels: Bug
