### ISSUE TITLE
search engine only checking names

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#619] opened 2016-03-15 20:38 UTC
hi

I have noticed that search engine is using only name to find the parts. Previous version 1.0.9 used name and description to find the parts. Is it any chance to change search engine to be at least same like 1.0.9. 

regards

**Comment by felicitus** [comment] 2016-03-15 20:39
Duplicate of #501

**Closed by felicitus** 2016-03-15 20:39 UTC
