### ISSUE TITLE
Broken Project secntion on demo

### ISSUE THREAD

**Issue by adis1987** [partkeepr/PartKeepr#785] opened 2017-01-14 19:59 UTC
Playing with the demo.pertkeepr.org and discovered a bug:

Project report -> Select a project -> Create report -> Autofill -> Remove part from stock

Now Project Report and Project Runs is not working.

**Comment by felicitus** [comment] 2017-01-17 18:04
I believe that the issue is now fixed, can you try again?

**Comment by adis1987** [comment] 2017-01-17 21:17
Looks like its working now

**Closed** 2017-01-21 19:04 UTC
