### ISSUE TITLE
Deleting user failed because of existing userpreferences

### ISSUE THREAD

**Issue by punkkeks** [partkeepr/PartKeepr#569] opened 2016-01-15 18:55 UTC
I cannot delete a (legeacy) user, when there are userprefences in the database. Maybe add a foreign ON DELETE CASCADE ?!

```
An error occurred

Details
==================================
An exception occurred while executing 'DELETE FROM PartKeeprUser WHERE id = ?' with params [18]:

SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partkeepr`.`UserPreference`, CONSTRAINT `FK_922CE7A2A76ED395` FOREIGN KEY (`user_id`) REFERENCES `PartKeeprUser` (`id`))

Request
==================================
DELETE /api/users/18?_dc=1452883707666

[object Object]

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"An exception occurred while executing \u0027DELETE FROM PartKeeprUser WHERE id = ?\u0027 with params [18]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`partkeepr`.`UserPreference`, CONSTRAINT `FK_922CE7A2A76ED395` FOREIGN KEY (`user_id`) REFERENCES `PartKeeprUser` (`id`))"}

Server Configuration
==================================
doctrine_orm_version: 2.5.1
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.17-1~dotdeb+7.1
auto_start_session: true
maxUploadSize: 8388608
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
```

**Comment by felicitus** [comment] 2016-02-04 17:16
Duplicate of #478

**Comment by felicitus** [comment] 2016-02-04 17:17
Sorry, not a duplicate

**Comment by felicitus** [comment] 2016-03-02 13:22
Unit tests and delete preferences are added, so I'll close the issue.

**Closed by felicitus** 2016-03-02 13:22 UTC
Labels: Bug
