### ISSUE TITLE
Error in DB after deleting parts from projects

### ISSUE THREAD

**Issue by Aleksei13jul** [partkeepr/PartKeepr#637] opened 2016-04-06 03:35 UTC
Hi,

Reproducing:
- go to demo.partkeepr.org,
- choose a project (i.e. PolyDAC),
- delete any three parts,
- press 'Save Projects',
- click on another project to refresh and go back,
- the error message appears:

An error occurred

Details
==================================
Error: Call to a member function getName() on null

Request
==================================
GET /api/projects/5?_dc=1459913672879

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Error: Call to a member function getName() on null"}

Server Configuration
==================================
doctrine_orm_version: 2.5.1
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.19-1~dotdeb+7.1
auto_start_session: true
maxUploadSize: 2097152
availableImageFormats: JPG,GIF,PNG
autoLoginUsername: admin
autoLoginPassword: admin
motd: <p><b>Welcome to the PartKeepr demo site</b></p>
<p>
Notes:
<ul>
<li>This PartKeepr installation is rebuilt from the GIT sources at every full hour</li>
<li>Rebuild takes about one minute, and you'll receive errors during rebuild</li>
<li>The database is synced from Felicitus' personal database, which might contain german part names or other odd stuff</li>
</ul>
</p>
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

**Comment by Aleksei13jul** [comment] 2016-04-06 03:41
Actually, the "ProjectPart' table has inconsistent data.
The rows with 'deleted' parts have 'project_id' = null, which is not allowed and produces the error.
Manual deleting of these rows helps in urgent case.

**Comment by felicitus** [comment] 2016-04-17 16:17
I believe the issue is now fixed. Can you try if it works for you on the demo system?

**Comment by Aleksei13jul** [comment] 2016-04-25 16:04
Hi Felicitus,

I have tried that, and had no trouble.
Looks okay.
Thank you indeed!

**Closed** 2016-04-25 16:05 UTC
