### ISSUE TITLE
Chromebook interface issue

### ISSUE THREAD

**Issue by fisherrs** [partkeepr/PartKeepr#945] opened 2018-01-25 20:50 UTC
[comment]: # (Hi and thanks for an issue. In order to help you best, please fill out the following information.)
Hi, I have a colleague that uses a chromebook and is unable to properly navigate my instance of PartKeepr or the demo site. He is unable to click anything. It highlights like he clicked, but does not proceed as if one had clicked the button or area. Not sure it this is Partkeepr specific or a php issue with chromebooks, but I have another server running a php application that doesn't have this issue.

# System Information

* PartKeepr Version: 1.3
* Reproducible on the demo system: Yes

# How to reproduce

Using any ChromeOS device, log into a PartKeepr instance. Any clickable button or selection area will be selected but not "clicked". Using the spacebar and enter key normally works on the top menu, but most other places dont.

**Comment by vrabcak** [comment] 2018-01-25 21:07
I have observed the same behavior on Firefox / Win10. The problem is quite
rare (once in several days) and disappears randomly after reload.

**Comment by UniversityOfPi** [comment] 2018-02-20 01:45
This behavior is near constant on the demo site (in my experience on a chromebook).

**Comment by torburger** [comment] 2018-06-28 04:45
This issue is constant for me in firefox on Arch linux 4.17.2-1 and ff 61.0. 

Some buttons, like Parts List or Thumbnail View become selected, but not clicked when I attempt to click them. I can then hit enter/space to "click" the item, annoying but it works. Other buttons, like the x to close windows isn't even selected  it seems, as I can't "click" those buttons by selecting them with the mouse and using space/enter.

**Comment by Drachenkaetzchen** [comment] 2018-06-28 05:06
@UniversityOfPi I do not own a chromebook, as such I can't reproduce the issue

@torburger 
> This issue is constant for me in firefox on Arch linux 4.17.2-1 and ff 61.0.

I can't reproduce the issue on FF 61.0 with the same arch kernel on https://demo.partkeepr.org.

**Comment by Drachenkaetzchen** [comment] 2018-06-28 05:09
All affected users: Please have a look in your JavaScript console if there are any errors (usually F12 on most browsers) and report these errors here.

**Comment by Drachenkaetzchen** [comment] 2018-06-28 05:11
Also please ensure that, for debugging and reproducing, that you have '''all addons disabled''' . I suspect it's an issue with addons.

**Comment by worm6666** [comment] 2018-08-22 08:13
on FIREFOX also - now it happens on my instance = local and demo also... no LEFT CLICK reaction on anything... :-( it is unusable, no console warning or error because of impossibility to click on anything

**Comment by christianlupus** [comment] 2020-01-15 15:15
Is this issue still valid? Please verify with the latest version.

**Comment by baradhili** [comment] 2020-01-28 04:08
Closing as 1. its old, 2. its was rare then and appears to be a browser addon

**Closed by baradhili** 2020-01-28 04:08 UTC
Labels: Bug, Feedback Needed, Frontend, Will be closed soon!
