### ISSUE TITLE
No composite values in params

### ISSUE THREAD

**Issue by nicknugget** [partkeepr/PartKeepr#390] opened 2015-02-18 17:51 UTC
It is impossible to use composite values like "hFE = 20..70" or "Tii = .65-100°C" in the parameters-table of a part. It's also impossible to enter a value without a unit. While there may be cases in which someone would like to do so or has to.
##

**Comment by felicitus** [comment] 2015-10-16 09:38
I agree. Textual or from-to values aren't possible. This is related to #54

**Comment by felicitus** [comment] 2017-01-07 11:21
I believe the issue is now fixed with the new part parameters:

![image](https://cloud.githubusercontent.com/assets/162974/21741369/c764d9a0-d4d3-11e6-850e-cf48501e1e97.png)

I'll close the issue. If you feel that the issue isn't solved, please re-open.

**Closed** 2017-01-07 11:21 UTC
Labels: Feature Request
