### ISSUE TITLE
invalid response from server

### ISSUE THREAD

**Issue by stegl** [partkeepr/PartKeepr#1128] opened 2020-05-27 10:32 UTC
I have problem installing partkeeper. I for some reason cant downgrade php to any other version... 

the first problem is this:
> Invalid configuration for path "monolog.handlers.main": Warning: count(): Parameter must be an array or an object that implements Countable

i tryed to fix it by:

> go to file -> /vendor/symfony/monolog-bundle/DependencyInjection/Configuration.php
> 
> around line 594 comment out or remove line below:
> 
> // ->ifTrue(function ($v) { return ('fingers_crossed' === $v['type'] || 'buffer' === $v['type'] || 'filter' === $v['type']) && 1 !== count($v['handler']); })
> 
> add the following line:
> ->ifTrue(function ($v) { return ('fingers_crossed' === $v['type'] || 'buffer' === $v['type'] || 'filter' === $v['type']) && (empty($v['handler']) || !is_string($v['handler'])); })

but just get this err:
![err](https://user-images.githubusercontent.com/65857447/82893176-e7993900-9f50-11ea-9da8-b5b000818306.png)

**Comment by christianlupus** [comment] 2020-05-30 07:07
OK, then let's discuss this here. Sorry for being late on it as I was busy with my day job recently.

> I for some reason cant downgrade php to any other version...

If this is a hard fact you are probably out of luck here. The issue is not that there is documentation missing or that we want to keep you from doing it but that some dependencies are heavily outdated. We are trying to get things running again but it takes time. Also, the manpower is quite small for any help would be welcome.

Your suggested changes in `/vendor/*` are nothing more than a hack that I'd rather not take. All bundles under `/vendor` are fixed releases of some foreign software. You must be very aware of the side-effects if you are doing this sort of thing.

Are you running on Linux with root rights? In this case, docker might be a solution as it allows you to install a subsystem with a completely different PHP version without interference with your main system. Are you willing to go this route? Do you need help here?

**Comment by stegl** [comment] 2020-06-03 21:41
no problem.. i had alot of other work to do anyways. 

well im thinking to install it on virtual mahine. 

> Are you running on Linux with root rights? In this case, docker might be a solution as it allows you to install a subsystem with a completely different PHP version without interference with your main system. Are you willing to go this route? Do you need help here?

yes i can install any linux.. this debian i have right now have so many problems ffs i and i dont know why and how to fix it..(cant install anything -.-) 
please if you can and have time i would like to install older version of php with that needed modules and i didnt find the working solution yet. 

i never used docker but it looks like ill need to start using it. 

thanks for any response in advance and sorry for my late respond. Have a nice day.

**Comment by christianlupus** [comment] 2020-06-05 15:44
It seems like your operating system is broken in general. You might want to fix it before you install new software. Docker needs an install as well but after that, you can think of an advanced chroot setting.

There is a docker package from mhubig that is your best bet at the moment. This repo will provide docker images eventually but these are not stable at the moment of writing. If you have any specific questions, feel free to ask them.

**Comment by stegl** [comment] 2020-06-06 14:44
i reinstalled debian and its broken again.. cant install anything -.- 

a vm would be nice and easy solution.. but its only for virtualbox and cant convert it for hyper-v. 

can be closed and deleted. 

Thanks for your replays. Have a nice day.

**Comment by christianlupus** [comment] 2020-06-09 05:46
> i reinstalled debian and its broken again.. cant install anything -.-

OK, this sounds strange. Yet, I think you were better of with a closer communication way (-> IRC?). If you want to do so, I might be able to help you in a live session.

> a vm would be nice and easy solution.. but its for virtualbox and cant convert it for hyper-v.

I would go with VirtualBox as Hyper-V is only compatible with a few (outdated) versions of windows as far as understand.

> can be closed and deleted.

If I understand you correctly you mean this issue? Below this text box there is a button close you can click as the author of the issue. I will close it but if this was my wrong understandung, I can still reopen without a problem. Just write me a message, ok?

> Thanks for your replays. Have a nice day.

You are welcome.

**Closed by christianlupus** 2020-06-09 05:46 UTC
Labels: Feedback Needed, Will be closed soon!, help-requested
