### ISSUE TITLE
Changing a Project

### ISSUE THREAD

**Issue by fulcrum3d** [partkeepr/PartKeepr#585] opened 2016-02-01 03:11 UTC
Hello Felicitus,

we currently have problems with Projects. When i want to for example, delete a part from any Project, an Error comes up. This applies to all possible changes you can make to a created project.
It seems like it has something to do with the Java Script, as it doesn't occur in the Demo version.

I'll attache a Screenshot. Maybe you can help us. 

Cheers
![untitled](https://cloud.githubusercontent.com/assets/16024295/12707883/a20dcb14-c8ed-11e5-83c1-3250dbd5ea75.png)
![untitled2](https://cloud.githubusercontent.com/assets/16024295/12707884/a2d96012-c8ed-11e5-9b08-ae4820d2122e.png)

**Comment by dylanjacob** [comment] 2016-02-02 17:37
This looks like what we have been talking about in #579

**Comment by fulcrum3d** [comment] 2016-02-02 22:56
thanks @dylanjacob!

**Comment by felicitus** [comment] 2016-03-08 15:17
Closing as duplicate of #579

**Closed by felicitus** 2016-03-08 15:17 UTC
