### ISSUE TITLE
BUG: Stock Level Info in the Details View is not Updated.

### ISSUE THREAD

**Issue by squintz** [partkeepr/PartKeepr#682] opened 2016-06-30 17:09 UTC
Adding or Removing stock does not update the Stock Level in the Part Details view. The stock within the main grid is updated so a current workaround is as follows:  Click the Add Stock or Remove Stock buttons as needed, make your changes and press okay. Then open the Edit Part Dialog from the main grid and  press save. This will update the Stock Level in the Part Detail View.

Whoever fixes this, while you are in there you might want to rename the title of the Add and Remove stock dialog to "Add Stock" and "Remove Stock" instead of Add Parts and Remove Parts for consistency.

**Comment by felicitus** [comment] 2016-08-18 14:21
I believe the issue is now fixed, can you confirm?

**Comment by felicitus** [comment] 2016-09-23 12:35
No feedback given, I assume it's fixed. If that's not the case, please re-open.

**Closed by felicitus** 2016-09-23 12:35 UTC
Labels: Feedback Needed
