### ISSUE TITLE
UI scrambled after deleting a part

### ISSUE THREAD

**Issue by alainstucki** [partkeepr/PartKeepr#740] opened 2016-10-23 21:17 UTC
hi all,
1. open https://demo.partkeepr.org
2. select a random part and delete it
3. click on another random part and the UI gets scrambled

![screen shot 2016-10-23 at 23 14 10](https://cloud.githubusercontent.com/assets/6509248/19629471/71665940-9976-11e6-8664-0e6ad72a91c8.png)

this happens on freshly installed v1.1.0 as well on the demo system.
tested on chrome, firefox and internet explorer/edge. 
the only way to get it working again is to reload the page and log in again

chrome developer tools complaining about the following error:
Uncaught TypeError: Cannot read property 'getRange' of null

**Comment by felicitus** [comment] 2016-10-24 13:48
I believe the issue is now fixed. Can you try it out on the demo system in about 20 Minutes?

**Comment by alainstucki** [comment] 2016-10-24 18:44
hi felicia

works perfect now, thx :)

**Closed** 2017-01-17 18:14 UTC
Labels: Bug
