### ISSUE TITLE
Default column presets for grids

### ISSUE THREAD

**Issue by Drachenkaetzchen** [partkeepr/PartKeepr#863] opened 2017-05-27 14:35 UTC
Right now, column presets revert to their defaults configured in the code. It would be good if the desired column preset would be stored in the user preferences.

**Comment by kjetilpp** [comment] 2018-07-15 16:01
Any update to this`?

**Comment by Drachenkaetzchen** [comment] 2018-07-15 16:33
No, it's done when it's done

**Comment by baradhili** [comment] 2020-03-01 04:51
duplicate of #1100  closing this one as 1100 has more details

**Closed by baradhili** 2020-03-01 04:51 UTC
Labels: Feature Request, Frontend

**Comment by Satnet** [comment] 2023-10-20 11:10
> No, it's done when it's done

5 years later and I'm waiting patiently. :)
