### ISSUE TITLE
Incorrect quantity when duplicating parts

### ISSUE THREAD

**Issue by DTFUHF** [partkeepr/PartKeepr#737] opened 2016-10-09 21:35 UTC
When duplicating parts (instead of creating a new part) and the initial quantity value is set to 0, the quantity of the new part is incorrectly reported.

Doing a stock transaction (add/remove quantity) on this part will subsequently show the correct quantity including the stock transaction.

Additionally, if the initial value is a negative number, the stock is set to zero.

Steps to reproduce (performed on demo server)
1. Find an existing part with nonzero quantity.
2. Duplicate this part and enter 0 or negative initial quantity.
3. View the new part, with stock count matching the original part.

3a. Optionally do a Project Report containing the new part and view the incorrect quantity. (This is how I found the bug - I knew I had to order this one part although the Project Report indicated I had sufficient quantity.)

4 . Perform a stock transaction on the new part (i.e. add one qty to stock)

5 . View the new part which has correct quantity displayed (i.e. 0 original plus 1 added)

**Comment by felicitus** [comment] 2017-01-31 15:24
It seems that the issue is now fixed. Can you double-check on the demo system if the problem is solved for you?

**Comment by DTFUHF** [comment] 2017-02-01 13:40
Hey, I went to the demo server to try this out, but I'm unable to duplicate parts, or even search, seems there is something unrelated going on. I'll try again later.

**Comment by christianlupus** [comment] 2020-01-18 17:16
I tried and could not reproduce. @DTFUHF could you please check once more?

**Closed** 2020-01-23 01:14 UTC
Labels: Feedback Needed, Will be closed soon!
