### ISSUE TITLE
No staggered prices

### ISSUE THREAD

**Issue by nicknugget** [partkeepr/PartKeepr#391] opened 2015-02-18 17:54 UTC
It would be nice, if staggered prices could be used in the distributors-section. Like in part-db. Many distributors have staggered prices, if you order larger quantities.

**Comment by scrupeus** [comment] 2015-08-14 11:45
Duplicate of #365

**Comment by felicitus** [comment] 2015-10-16 09:36
Indeed a duplicate, closing this one.

**Closed by felicitus** 2015-10-16 09:36 UTC
Labels: Feature Request
