### ISSUE TITLE
Unable to add Parameters

### ISSUE THREAD

**Issue by lookme2** [partkeepr/PartKeepr#512] opened 2015-12-01 19:30 UTC
I do not have the ability to add Parameters to my parts?  I can insert new ones but there is nothing to select.

**Comment by felicitus** [comment] 2015-12-03 09:16
I can confirm the issue.

**Comment by felicitus** [comment] 2015-12-03 09:24
Error seems to be: `Uncaught TypeError: Cannot read property 'siprefix_id' of undefined`

**Comment by felicitus** [comment] 2015-12-15 11:08
Development notices:
- The `SiUnitField` uses legacy code
- It's not possible to set a record's field to arbitrary values; for that purpose, an internal relation is required so that the `SiUnitField` can return an object with all required data

**Comment by jyepesr1** [comment] 2016-02-25 15:44
@felicitus I've the same problem. I can't save any parameter for these issues, How can I fix that?

1. GET http://localhost/PartKeepr/web/Part/getPartParameterNames?
_dc=1456414964745&page=1&start=0&limit=25 500 (Internal Server Error)

2. Uncaught TypeError: Cannot read property 'siprefix_id' of undefined

Thank You

**Comment by felicitus** [comment] 2016-02-25 16:41
@jyepesr1 it is a bug, which cannot be fixed by you unless you have knowledge of the PartKeepr internals and willing to provide a bugfix.

**Comment by felicitus** [comment] 2016-03-09 15:06
I've decided to disable the part parameters as they need to be refactored, which is a huge effort.

**Comment by felicitus** [comment] 2016-03-09 15:06
Part Parameters will be re-introduced at a later point in time.

**Comment by felicitus** [comment] 2017-01-17 18:50
Advanced Part Parameters are now implemented, thus I believe this issue can now be closed.

**Closed by felicitus** 2017-01-17 18:50 UTC
Labels: Bug, Frontend
