### ISSUE TITLE
Error: Call to a member function getType() on null

### ISSUE THREAD

**Issue by adis1987** [partkeepr/PartKeepr#592] opened 2016-02-10 08:24 UTC
Created a project and saved it. Then I make some updates and trying to save it again (V0.78):

```
An error occurred

Details
==================================
Error: Call to a member function getType() on null

Request
==================================
PUT /api/projects/2?_dc=1455092290890

[object Object]

Response Status Code
==================================
500

Response
==================================
{"@context":"\/api\/contexts\/Error","@type":"Error","hydra:title":"An error occurred","hydra:description":"Error: Call to a member function getType() on null"}

Server Configuration
==================================
doctrine_orm_version: 2.5.1
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 5.6.11-1ubuntu3.1
auto_start_session: true
maxUploadSize: 33554432
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

```

**Comment by felicitus** [comment] 2016-02-10 13:28
Duplicate of #579

**Closed by felicitus** 2016-02-10 13:28 UTC
