### ISSUE TITLE
Wrong filenames for uploaded attachments

### ISSUE THREAD

**Issue by nicknugget** [partkeepr/PartKeepr#389] opened 2015-02-18 17:42 UTC
When an attachment (e.g. datasheets) gets uploaded, the attachment has afterwards the wrong filename. It seems, that the system takes temp-filenames for storing, instead of the original filename.

**Comment by felicitus** [comment] 2015-07-17 16:05
I just tried to reproduce this in the demo system, but it works for me as expected. I assume that this was already fixed in the GIT version. Can you try to reproduce this on the demo system at http://demo.partkeepr.org ? Thank you!!

**Comment by nicknugget** [comment] 2015-08-16 16:37
I've uploaded a data sheet in the demo system and there it works now as expected! 
So I'm waiting for the upcoming stable release. 
Thank you!

**Comment by felicitus** [comment] 2015-10-16 09:38
Cool, I'll close the issue then.

**Closed by felicitus** 2015-10-16 09:38 UTC
Labels: Bug, Feedback Needed
