### ISSUE TITLE
partkeepr 1.1.0 refreshing issue

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#781] opened 2017-01-11 23:08 UTC
hi

I have noticed refresh site problem after thumbnail view. Demo has the same problem. You can check like that: After login please go straight to thumbnail view in root folder . Later one choose  Part list : Mosfet, NPN, PNP and jump between them. Page does not want to refresh at all 

Regards

**Comment by felicitus** [comment] 2017-01-11 23:10
I'm having trouble understanding what exactly you mean by refreshing. What exactly does not refresh? Where exactly do you click?

**Comment by mctomaszek** [comment] 2017-01-11 23:11
please click thumbnail view...and later one try to check stock transitor: mosfet, npn, pnp

**Comment by felicitus** [comment] 2017-01-11 23:16
I still can't reproduce or understand what the issue is. What do you mean with "mosfet, npn, pnp?" Do you mean the categories?

Example of a good report (and what I have done according to your issue report):
- I click the "Thumbnail Tab"
- I click the first image
- Part Details Panel opens and displays the information for that image
- I click on "Stock History" which shows the exact stock history for that part
- I click on the second and third image. The Part Details Panel refreshes with the information of the new part
- I click on the NPN category and the thumbnail view refreshes to display only parts from that category

**Comment by mctomaszek** [comment] 2017-01-11 23:21
![1](https://cloud.githubusercontent.com/assets/13379408/21870513/aa705e8a-d854-11e6-8643-e45741f33a8e.jpg)

**Comment by mctomaszek** [comment] 2017-01-11 23:21
![2](https://cloud.githubusercontent.com/assets/13379408/21870523/ba2f79a0-d854-11e6-97c0-83c10eb09613.jpg)

**Comment by mctomaszek** [comment] 2017-01-11 23:22
loading .............and loading...never ending story:(

**Comment by felicitus** [comment] 2017-01-11 23:52
How to reproduce:

1) Click the `Thumbnail View Tab`
2) Click the `Parts List Tab`
3) Choose any category

An error in the JS console is thrown:
```
extjs.js:22 Uncaught TypeError: Cannot read property 'internalId' of undefined
    at E.updateIndexes (extjs.js:22)
    at E.onAdd (extjs.js:22)
    at E.fire (extjs.js:22)
    at E.doFireEvent (extjs.js:22)
    at E.a.doFireEvent (extjs.js:22)
    at E.fireEventArgs (extjs.js:22)
    at E.fireEvent (extjs.js:22)
    at E.onCollectionAddItems (extjs.js:22)
    at E.onCollectionAdd (extjs.js:22)
    at E.notify (extjs.js:22)
```

**Comment by mctomaszek** [comment] 2017-01-12 10:48
hi
could you let me know please it is any simply fix for it or we should wait for new version of parkeepr ?

regards

**Comment by felicitus** [comment] 2017-01-14 18:26
Sorry no simple fix yet, I will update the post as soon as I got a fix. Scheduled for 1.2

**Comment by mctomaszek** [comment] 2017-01-14 19:24
thank U ....

**Comment by adis1987** [comment] 2017-01-14 20:04
Having the same problem on 1.1.0

**Comment by mctomaszek** [comment] 2017-01-30 14:30
looks like demo version does not have any more this issue.....just gone :)....at least I can't reproduce as well

any way ....demo version it is not rebuild at full hour any more

regards

**Comment by adis1987** [comment] 2017-01-30 18:51
The demo doese not have the issue.

Im using version 1.1.0

When I log in and every thing hase loaded:
1. I click on the Thumbnail View -> The images is loaded
2. Now I want to go back and view component in line -> Click Part List -> now the loading popup is showing and the page is broken. To make it work the solution is to reload the page and login again.

**Comment by mctomaszek** [comment] 2017-01-30 19:42
I have also problem with version 1.1.0.... and everyone who is using this version as well . My question is ....did you see title?  "partkeepr 1.1.0 refreshing issue".........Please read whole discussion about is...  later you will be know what Felicitus said about it. Last time he added themes option and "Thumbnail View" issue disappeared  somehow form Demo version

felicitus commented 16 days ago
Sorry no simple fix yet, I will update the post as soon as I got a fix. Scheduled for 1.2

**Comment by felicitus** [comment] 2017-09-03 18:03
PartKeepr 1.3.0 was just released, can you check if it works for you now?

**Comment by christianlupus** [comment] 2020-01-18 17:10
No answer in the last 2 years. So closing now.

**Closed by christianlupus** 2020-01-18 17:10 UTC
