### ISSUE TITLE
Feature request: Prevent partkeepr from generating a bunch of default folders filled with footprints on a database wash

### ISSUE THREAD

**Issue by DeniTCH** [partkeepr/PartKeepr#986] opened 2018-07-18 12:14 UTC
# System Information

* PartKeepr Version: 1.4.0
* Reproducible on the demo system: have not tried.

# How to reproduce

Whenever you do a database wash, or update Partkeepr to a new version it autogenerates a bunch of folders inside the footprint tree filled with default footprints. These are really cumbersome to remove every time.

![capture](https://user-images.githubusercontent.com/9782597/42880424-8d583a04-8a94-11e8-8890-e59333b217c2.PNG)

**Comment by Drachenkaetzchen** [comment] 2018-07-18 12:36
Duplicate of #901

**Closed by Drachenkaetzchen** 2018-07-18 12:36 UTC
