### ISSUE TITLE
Partkeepr creating window in window

### ISSUE THREAD

**Issue by philm001** [partkeepr/PartKeepr#707] opened 2016-08-08 15:48 UTC
Hello everyone,

I seem to having a bug with partkeepr. When I add/remove stock or add a new part or edit and existing part, partkeepr adds it succussfully. However, when I go to repeat the action, partkeepr creates another window at the very bottom of the screen. It is as if partkeepr is expanding the frame to make the window fit. I am also unable to save any changes.

I created a post on the google groups and I will link it to this issue:

https://groups.google.com/forum/#!topic/partkeepr-users/2NAb0moK11U

This happens for Mac OS X and Windows 10 using safari, google chome, firefox, and Edge. The issue can kinda be fixed by refreshing the page. However, this makes the process slower. 

This did not happen when partkeepr was first installed. It took at least 3-5 days for it to show up. We have about 6 computers needing to access partkeepr. All of the computers did not see the issue on the same day. Some took longer for the issue to appear. Others, sooner.

I should also mention that partkeepr is install on a ubuntu 14.04 virtualbox. The computer that the virtualbox is installed on does not have this issue.

**Comment by felicitus** [comment] 2016-08-08 15:49
Can you reproduce it on the demo site?
Do you receive any JavaScript errors in your JavaScript console?

**Comment by philm001** [comment] 2016-08-08 20:51
I do not think that I can reproduce it on the demo site. I can certainly try later today though.

I do not receive any JavaScript errors

**Comment by philm001** [comment] 2016-08-09 12:57
Also, I should note that I am using version 1.0

**Comment by philm001** [comment] 2016-08-09 13:39
Also, we are using php 7, the latest version, on our server

**Comment by felicitus** [comment] 2016-08-09 13:39
Can you post a screenshot of the JavaScript console after the error occurs? It's very hard to fix a bug which I can't reproduce.

**Comment by philm001** [comment] 2016-08-09 13:59
Sure, is there any specific command that I can run in the console to get some debugging information?

**Comment by felicitus** [comment] 2016-08-09 14:01
No, everything is printed on the JS console. See https://wiki.partkeepr.org/wiki/How_to_Debug#Frontend_Debugging on how to open the JavaScript console. Firefox and Chrome are preferred. Open the console before the problem happens. You should at least see several informational messages like "For WAI-ARIA compliance, IMG elements SHOULD have an alt attribute.".

**Comment by philm001** [comment] 2016-08-09 14:34
Oh, I see. I apologize for that. Here is the error I recieve when I go through a normal routine of adding a part and editing another:

extjs.js:22 Uncaught InvalidCharacterError: Failed to execute 'setAttribute' on 'Element': '"' is not a valid attribute name.

**Comment by philm001** [comment] 2016-08-09 14:54
[consoleLog.txt](https://github.com/partkeepr/PartKeepr/files/409206/consoleLog.txt)

Here is the log file

**Comment by philm001** [comment] 2016-08-09 14:56
And here is an expanded view of the error
![errorlog](https://cloud.githubusercontent.com/assets/13646291/17521054/ec0dbd06-5e1f-11e6-87e2-15c02dff6e40.jpg)

**Comment by philm001** [comment] 2016-08-10 14:40
Is there any more information that I can provide?

I am thinking of attempting to reinstall partkeepr and see if this helps

**Comment by felicitus** [comment] 2016-08-10 14:41
I haven't had time to analyze the information you sent. A reinstall certainly won't fix the issue, please wait until I got time to analyze the data.

**Comment by philm001** [comment] 2016-08-10 17:30
Ok, will do

**Comment by philm001** [comment] 2016-08-11 13:54
Hello felicitus, 

I was wondering if you had a chance to review the log files? I represent a company that is using partkeepr and we are currently grounded until the issue is addressed.

Is there anything that we can do on our side to ensure that our operations can continue?

**Comment by felicitus** [comment] 2016-08-11 18:21
@philm001 you could try to install the git version as per https://wiki.partkeepr.org/wiki/Running_PartKeepr_from_GIT - for everything else you unfortunately have to wait until I get around it or seek commercial support as per https://partkeepr.org/support/commercial

**Comment by philm001** [comment] 2016-08-11 20:19
Ok, I am hoping that this is the case. I will attempt to compile and run from the git. Will let you know how it goes

**Comment by philm001** [comment] 2016-08-12 03:37
So here is our instructions for installing partkeepr on the virtual machine. These are the steps that we did. We wanted to have php 7.0 but I see components with for 5.6. I am wondering if this could have caused some issues?

https://docs.google.com/document/d/1eNIMb2hhcRcDmRz3wp3elahNo3NHCFnOU1RzuPW0Rgg/edit?usp=sharing

**Comment by felicitus** [comment] 2016-08-15 16:17
No, the PHP version doesn't have anything to do with the JavaScript frontend issue.

**Comment by philm001** [comment] 2016-08-17 19:54
Ok

Are there any issues on how we setup and installed partkeepr?

**Comment by christianlupus** [comment] 2020-01-18 20:01
@philm001 as there was  no more communication here, I assume the issue has somehow settled. If still an issue (especially on the demo page), please tell me, then I will reopen it.

**Closed by christianlupus** 2020-01-18 20:01 UTC
