### ISSUE TITLE
Current Project Status?

### ISSUE THREAD

**Issue by proffalken** [partkeepr/PartKeepr#1216] opened 2021-05-24 16:29 UTC
Hey all, I've seen #1059 and I understand that there were personal reasons for the project stalling slightly, however I'm looking at the code base and the number of open issues/PR's and wondering if there's an update?

I've spent a significant amount of time over the past few days trying to get this up and running in Docker via multiple different images with no success, and it seems that the latest release of the project (from which most of the containers are based) is *not* the same as the code in the master branch.

The master branch hasn't been merged to since February, so I'm wondering if this is the right project on which to base my home inventory.

The system looks amazing, and given that the alternatives are basically partsbox.com (great, but no API I can hook in to) or Odoo (massively overkill for keeping track of a few components on a shelf in the garage and a constant attempt to upsell to the paid version!) I'd love to use Partkeepr, however I don't have the time to take on the maintenance of a project (and especially not one that's written in a language I don't use anymore!).

Please don't take this as a criticism, I'm sure there are good reasons for the current state of the project, I just want to know what the future holds if I decide to adopt it - I don't want to be left with an unmaintained system in two years time! :)

**Comment by hdt551** [comment] 2021-05-25 12:22
I switched from Partkeepr to Tryton (also overkill but it does let me keep track of purchases also).  Not easy but it might not be any harder than trying to get Partkeepr to run now.

**Comment by PTDreamer** [comment] 2021-05-25 13:07
I don't know what the issue is in getting this to run in a docker container. I'm using GIT version:d6e537eb  with Ubuntu 20.04.2 LTS  with PHP 7.4.3 and never had issues. I remember I just had to edit an installation file to bypass the PHP version check, but that was all.

**Comment by proffalken** [comment] 2021-05-26 08:04
> I don't know what the issue is in getting this to run in a docker container. I'm using GIT version:d6e537eb  with Ubuntu 20.04.2 LTS  with PHP 7.4.3 and never had issues. I remember I just had to edit an installation file to bypass the PHP version check, but that was all.

Thanks - is that a custom container you've built yourself, or one from docker hub?

It's the ones one docker hub that I've been struggling with.

**Comment by christianlupus** [comment] 2021-06-02 10:46
There is not really an update. A few persons try to migrate to a newer framework version that will allow more people to participate in the project. Additionally, this will make the installation on newer PHP and MariaDB versions possible and the mentioned checks can be lifted.

However, we are still only a few guys and we are using our spare time to get this project running. Honestly, the vast number of issues/PRs is an indicator that the progress is still stalling. Apart from that, if anyone is interested in helping out, you are free to join. Just send a message (here, in the other issue, IRC, direct mail,...). I am closing this issue here for now as is in fact a duplicate of #1059.

**Closed by christianlupus** 2021-06-02 10:46 UTC
Labels: help-requested, needs-triage

**Comment by proffalken** [comment] 2021-06-02 15:02
Thanks @christianlupus, update much appreciated, I'll keep a close eye on the project :)
