### ISSUE TITLE
Installer APCu check fails

### ISSUE THREAD

**Issue by PTDreamer** [partkeepr/PartKeepr#1131] opened 2020-06-12 18:55 UTC
APCu existence is checked on PartKeeprRequirements.php with `function_exists('apc_fetch')`.

apc_fetch is an apc function and is only present if apcu_bc module is installed.

If only apcu functions are needed a better check would be `function_exists('apcu_enabled')`.

**Comment by christianlupus** [comment] 2020-06-14 10:49
Duplicate of #1084.

**Closed by christianlupus** 2020-06-14 10:49 UTC
Labels: Bug, needs-triage
