### ISSUE TITLE
Project Reports Show Quantity of 0 in 1.0.0

### ISSUE THREAD

**Issue by lookme2** [partkeepr/PartKeepr#676] opened 2016-06-02 16:11 UTC
If you run a report the project report always shows a quantity of 0.  This also happens with the demo version.

**Comment by felicitus** [comment] 2016-06-02 16:14
can't reproduce. please describe the exact steps you've taken. 

Am 2. Juni 2016 18:11:37 MESZ, schrieb lookme2 <notifications@github.com>:
>If you run a report the project report always shows a quantity of 0. 
>This also happens with the demo version.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/partkeepr/PartKeepr/issues/676

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lookme2** [comment] 2016-06-02 16:22
Open Demo site
View>Project Reports
Select a report with a Check mark and Set a quantity
Click Create Report Button
Project report shows a Quantity of 0 on each part

**Comment by felicitus** [comment] 2016-06-02 17:20
You need to click "Autofill" in order to fill the "Amount to order" field.

Steps I've taken:
* Open Demo Site
* Click View>Project Reports
* Clicked the "Quantity" field of YuSynth Steiner VCF and entered 1
* Ensured that the checkbox in front of the project is active
* Clicked "Create Report"
* "Create Report" shows the correct quantity in column 1 and a quantity of 0 in "Amount to Order"
* Clicked "Autofill", which fills the report with data of "Amount to order"

![image](https://cloud.githubusercontent.com/assets/162974/15754097/d714c204-28f6-11e6-8462-d08f12a16417.png)

**Comment by lookme2** [comment] 2016-06-02 18:29
I followed you instructions.  It did not work on my end.  I am using Win10 with Edge.  Here is a screen shot. 

    On Thursday, June 2, 2016 12:20 PM, Felicia Hummel <notifications@github.com> wrote:
 

 You need to click "Autofill" in order to fill the "Amount to order" field.Steps I've taken:   
   - Open Demo Site
   - Click View>Project Reports
   - Clicked the "Quantity" field of YuSynth Steiner VCF and entered 1
   - Ensured that the checkbox in front of the project is active
   - Clicked "Create Report"
   - "Create Report" shows the correct quantity in column 1 and a quantity of 0 in "Amount to Order"
   - Clicked "Autofill", which fills the report with data of "Amount to order"

**Comment by felicitus** [comment] 2016-06-02 20:30
I don't have Edge, the demo works fine in IE11. The screenshot wasn't attached, you need to upload it within the issue on GitHub.

**Comment by lookme2** [comment] 2016-06-03 12:53
@felicitus Sorry about the attachment.   Here it is.  It works fine in Fire Fox  and IE11.

![capture](https://cloud.githubusercontent.com/assets/11365211/15779075/ea0135b4-295f-11e6-901c-3ecbab65dda0.PNG)

**Comment by felicitus** [comment] 2016-06-05 16:15
In the screenshot you've pasted you entered 1 in "YuSynth Steiner VCF" but ticked "YuSynth LFO-1" with a quantity of 0. That's why the quantity is 0.

**Comment by lookme2** [comment] 2016-06-07 12:49
Felicia
Sorry about that...   Here is a new screen  shot. Still get the same results. 

    On Sunday, June 5, 2016 11:15 AM, Felicia Hummel <notifications@github.com> wrote:
 

 In the screenshot you've pasted you entered 1 in "YuSynth Steiner VCF" but ticked "YuSynth LFO-1" with a quantity of 0. That's why the quantity is 0.—

**Comment by felicitus** [comment] 2016-06-07 12:50
You need to upload screenshots to GitHub directly. Replying to a GitHub message with an attachment will not work.

**Comment by lookme2** [comment] 2016-06-07 20:22
![capture](https://cloud.githubusercontent.com/assets/11365211/15873282/8ec0f650-2cc3-11e6-8969-1220d2318e21.PNG)

**Comment by felicitus** [comment] 2016-06-07 20:30
I just tested it using the Edge browser on a Windows 10 machine, but I can't reproduce the issue.

**Comment by lookme2** [comment] 2016-06-13 16:33
Sorry been pretty busy.  I have a couple of other Win10 machines I can check.  I'll do that today and report back.

**Comment by felicitus** [comment] 2016-06-13 16:46
thank you. if possible can you record a screen cast? maybe there's a problem with the user experience. 

Am 13. Juni 2016 18:33:05 MESZ, schrieb lookme2 <notifications@github.com>:
>Sorry been pretty busy.  I have a couple of other Win10 machines I can
>check.  I'll do that today and report back.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/partkeepr/PartKeepr/issues/676#issuecomment-225635668

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by felicitus** [comment] 2016-08-02 12:58
No feedback given for an extended period of time, closing. Please re-open if required.

**Closed by felicitus** 2016-08-02 12:58 UTC
