### ISSUE TITLE
synctips cronjob issue

### ISSUE THREAD

**Issue by Drachenkaetzchen** [partkeepr/PartKeepr#862] opened 2017-05-27 14:32 UTC
When the PartKeepr servers are not able to deliver tips, the cronjob is marked as not being run.

This needs to be fixed. Affects #850 and #858

**Comment by baradhili** [comment] 2020-01-15 03:38
Vague?

**Comment by baradhili** [comment] 2020-01-15 03:40
Duplicate of #850

**Closed** 2020-01-27 04:37 UTC
Labels: Backend, Bug
