### ISSUE TITLE
Memory leak in frontend

### ISSUE THREAD

**Issue by scrupeus** [partkeepr/PartKeepr#241] opened 2012-07-17 06:56 UTC
Frontend memory use steadily increases with time, even without user interaction.  Usage starts at about 65 MB, increases to 130 MB after 2-3 hours and continues to > 1 GB after many hours.  This occurs with both Firefox and Chrome/Chromium.

CPU usage also increases with time - from 1% initially to 2% after 2-3 hours and 5+% over longer periods.  On an Atom processor, usage is 80+% after just a few hours.

**Comment by felicitus** [comment] 2015-10-16 09:55
Reminder for me to let a chrome window sit for several days and see if the memory usage increases significantly on ExtJS6.

**Comment by felicitus** [comment] 2016-04-17 16:41
I believe the issue is now fixed.

**Closed by felicitus** 2016-04-17 16:41 UTC
Labels: Bug
