### ISSUE TITLE
partkeeper / "parts without stock removals"  

### ISSUE THREAD

**Issue by bullyland** [partkeepr/PartKeepr#1111] opened 2020-04-11 10:15 UTC
parts without stock removals - filter is not working for me.
even in the demo it isn't working? anybody can help? thanks

**Comment by christianlupus** [comment] 2020-04-11 13:36
Dear @bullyland, unfortunately, it is unclear to me what your exact problem is.

Please provide the following information:
- What are you trying to do?
- How are you assuming this should work?
- What is happening?
- What do you expect of happening?

If you need a screenshot to explain your problem, you can add them here (use the demo page if you fear confidential information to be leaking).

All I understood is that some user functionality is neither working on your local instance nor on the demo page. Without more information, we cannot help.

**Comment by bullyland** [comment] 2020-04-11 13:38
hi! 

thanks for your answer. i mean if i use this filter > nothing happend....
you can also try on the demo site. i think it must show me unused 
parts or parts without removal? but it show me always all parts.

**Comment by christianlupus** [comment] 2020-04-11 14:06
Which filter? Sorry, this is still no useful information.

Please provide a complete step-by-step process to show what is going wrong. 

My last guess is you are referring to the stock level filter. See this screenshot:
![GitHub PartKeepr Issue 1111_1](https://user-images.githubusercontent.com/8202922/79045815-6d655d00-7c0d-11ea-930b-40f5a264d984.gif)

So, please, take your time, write in complete English sentences what your problem is in a clear and structured way. It should be in a way to give it to anyone on the street so that this person is capable to understand what you did **exactly**. Use a screenshot or screencast as I did if it helps you to describe the problem.

**Comment by bullyland** [comment] 2020-04-11 15:13
thanks again, no i mean this Filter:
![image](https://user-images.githubusercontent.com/63493154/79047565-1917a880-7c20-11ea-93da-5dab84b54862.png)

**Comment by bullyland** [comment] 2020-04-11 15:15
this "marked"filter: (over the "apply"button)

"Show Parts without stock removals only

he isn't working. not on my installation, not on the demo site.
and sorry for my bad english. best regards, i hope you can help...

**Comment by christianlupus** [comment] 2020-04-11 15:46
OK, now we are getting closer.

I tried it. It seems to work for me on the demo page. The `LM394H` is a device that had some removal in the past. You see it in the stock view of the part.
When I enable the filter you describe, the named part is hidden (as intended). I tried several other parts that are still visible. All these seem to be just created and added some stock. However, there was never taken anything from stock...

![GitHub PartKeepr Issue 1111_2](https://user-images.githubusercontent.com/8202922/79048182-8aa12800-7c1b-11ea-9bb3-8f0a5f62dbfa.gif)

The question is now: Did you do anything more? What did you expect to happen?

**Comment by christianlupus** [comment] 2020-04-11 15:55
OK, I just found your problem. This seems to be a bug in the Backend. I will open a new bug soon with all relevant information.

**Comment by bullyland** [comment] 2020-04-11 16:04
ok, thanks. how i will get to know if the problem is solved?

**Comment by bullyland** [comment] 2020-04-11 16:09
and one more question: how can i change the format of the time, you can see it on the part details
window on the right site of the screenshot. is very long and i want to change this, is this possible?

best regards

**Comment by christianlupus** [comment] 2020-04-11 16:09
I assume this will take some time. See #1056.
We try to get this project running again, but I cannot promise you anything.

**Comment by christianlupus** [comment] 2020-04-11 16:11
> and one more question: how can i change the format of the time, you can see it on the part details
> window on the right site of the screenshot. is very long and i want to change this, is this possible?

It is not yet possible as far as I know. This is a new feature request.

**Comment by christianlupus** [comment] 2020-04-11 16:34
I opened the two issues mentioned above which cover your problem hopefully. If there is something missing please leave me a note.

Otherwise I will close this issue now.

**Closed by christianlupus** 2020-04-11 16:34 UTC
Labels: Will be closed soon!, help-requested

**Comment by bullyland** [comment] 2020-04-12 04:02
thank you

**Comment by bullyland** [comment] 2020-04-13 05:25
hi again, i see there is nobody helping here:)?

**Comment by christianlupus** [comment] 2020-04-13 09:53
Hello @bullyland. What are you talking about? You had a set of issues reported. To get things sorted out, I split it into the various topics and opened following issues.

What are you expecting exactly?

**Comment by bullyland** [comment] 2020-04-13 16:54
why it is impossible to change the time format.... i work on all codes for 2 days.... i don't understand this? i think the format must be changable ? do you have any idea? maybe in mysql ?

**Comment by christianlupus** [comment] 2020-04-14 11:06
> why it is impossible to change the time format.... 

Simply because no one yet addressed the issue. There are a ton of other issues to be addressed and these are considered more important, especially because some are security relevant.

> i work on all codes for 2 days.... i don't understand this? i think the format must be changable ? do you have any idea? maybe in mysql ?

Definitively not in MySQL.

The dates are transferred from the backend in form of JSON data to the frontend in condensed form. It took me about 5 minutes to check this and to find [this](https://github.com/partkeepr/PartKeepr/blob/master/src/PartKeepr/FrontendBundle/Resources/public/js/Components/Part/PartDisplay.js#L83-L88) and [this](https://github.com/partkeepr/PartKeepr/blob/master/src/PartKeepr/FrontendBundle/Resources/public/js/Components/Part/PartInfoGrid.js#L25-L28) section.

You might want to have a look at how Ext handles the date conversion. It should be possible to affect it somehow. You are welcome to participate and provide a suggestion about how to change the code e.g. via pull request.

**Comment by bullyland** [comment] 2020-04-14 13:49
ok, thanks!
