### ISSUE TITLE
BUG: Saving Project Resets Stock Level

### ISSUE THREAD

**Issue by lazosweb** [partkeepr/PartKeepr#685] opened 2016-07-12 08:33 UTC
On the Demo.
1) Open the Projects tab and for example select the 14973 - Ecuador Project.
2) In that project the first Part is "IC-Socket, 16 pin, low profile, twisted, glided".
3) Go back to the Part Manager Tab and search for the above part.
4) Now Change the stock from 19 if it's 19 to 200 or whatever number you like and save it.
5) Now go back to the project tab and click "Save Project".
6) Go back to Part Manager and refresh the page and the stock level will reset back to 19.

Is this normal behavior?

My OS is Windows 7 64 bits.
I am using Firefox 47.0.1 we had the same problem with Chrome too and on a different PC.

Let me know if you need more information.

**Comment by tayfuncetin** [comment] 2016-07-12 11:56
I think it's about cache issue. If you refresh whole page. You will see that stock level is as it should be.

**Comment by lazosweb** [comment] 2016-07-12 12:10
I refreshed, I logged out and logged in and still the same problem. Partkeepr keeps getting the wrong stock number. Our department reported that other data are disappearing. I prepared a video https://www.youtube.com/watch?v=Y7jR6KyyoQs for @felicitus

**Comment by tayfuncetin** [comment] 2016-07-13 18:13
@lazosweb yes, I installed Partkeepr on my VPS and this issue is occuring there also. It is very important bug. Congrats that you could be aware of it. I hope that it may solve fastly.

**Comment by lazosweb** [comment] 2016-07-13 20:35
@tayfuncetin Well if you look into it in depth when it resets the stock level and if you try to change it again then it takes the reset value into account and then things are really getting messed up. I do not know I hope the developer will fix it ASAP because our Production Department is adding the stock into an excel file because of this bug, :)

**Comment by lazosweb** [comment] 2016-07-18 20:01
@felicitus if I may ask, are you planning to fix this bug?

**Comment by felicitus** [comment] 2016-07-18 21:16
Basically I'm planning to fix all the bugs in PartKeepr. However, as I'm maintaining the project in my spare time, it's impossible to predict when the bug is fixed.

If it's urgent you can always ask the PartKeepr UG to fix the bug.

**Comment by lazosweb** [comment] 2016-07-18 21:57
OK. Thanks for letting us know.

**Comment by felicitus** [comment] 2016-07-19 11:56
I scheduled the issue for 1.0.1 and gave it high priority

**Comment by felicitus** [comment] 2016-08-16 22:11
I believe the issue is fixed now - can you double check on the demo system in about one hour earliest?

**Closed** 2016-08-16 22:10 UTC
Labels: High Priority
