### ISSUE TITLE
set of items with nearly identical values/properties

### ISSUE THREAD

**Issue by maugsburger** [partkeepr/PartKeepr#142] opened 2012-02-07 18:02 UTC
I have many items in my collection, that are nearly the same, often sharing datasheet etc.

One example are "MBF 12,16,20", only some measurements are different.
Another exampel are "WAGO 273-100" etc that you can vary in "two dimensions": grey, black or transparent and 2-5 "ports". 

My Idea of implementation would be that you can create a part with a special flag "template" that normally doesn't get shown.
The real parts can be seen as implementations of this template, all values not set directly in this part are taken (as in linked, not copied!) from the template. 
##

**Comment by baradhili** [comment] 2020-01-16 10:23
Duplicate of #141 mostly, closing

**Closed by baradhili** 2020-01-16 10:23 UTC
Labels: Feature Request, Low Priority
