### ISSUE TITLE
Searching for Internal Part Number 

### ISSUE THREAD

**Issue by fulcrum3d** [partkeepr/PartKeepr#501] opened 2015-11-25 23:00 UTC
Hi,

after downloading the new update, i am not able to search for any other information besides the description. Why did you do that? That is a huge problem for us, as we track down our parts with the the internal part number. 

Would there a be way to make it possible to still search for the internal part number? Besides downgrading the software

thanks

**Comment by felicitus** [comment] 2015-11-25 23:04
I will have a look why this happens. If it's not a big issue, the fix will be included in the next release, due in a few days.

**Comment by fulcrum3d** [comment] 2015-11-26 06:13
Thank you.

Additionally, it would be useful to see in which projects a certain part is. (Like before) 
And we discovered that it is not possible to new parts to previously created projects. 

Cheers

**Comment by felicitus** [comment] 2015-11-26 11:01
Could you please open separate issues for each individual bug? Thank you

**Comment by felicitus** [comment] 2015-11-26 19:48
I can offer a quick fix where the internal part number can be searched by the part filter panel:

![image](https://cloud.githubusercontent.com/assets/162974/11429925/e7eb044c-947e-11e5-99d6-148a2de2443a.png)

I also plan on re-introducing the behaviour of 0.1.9, however, it's not possible to do a very quick fix.

**Comment by felicitus** [comment] 2015-11-26 19:49
Internal note: The 0.1.9 version did search the fields "comment", "name", "description" and "internalPartNumber". To make this work again, the AdvancedSearchFilter must be modified to allow OR queries. Right now, the AdvancedSearchFilter only allows AND queries.

**Comment by felicitus** [comment] 2015-11-26 19:55
@fulcrum3d if you wish to use the quick fix where you can use the part filter panel for searching the internal part number, you can replace the file `src/PartKeepr/FrontendBundle/Resources/public/js/Components/Part/PartFilterPanel.js` with the contents of https://github.com/partkeepr/PartKeepr/commit/49521214a1fd175b0d8582913959ac080f273059 and then re-run setup (or re-generate the environment as described [in the wiki](https://wiki.partkeepr.org/wiki/Developers/Re-generating_the_environment))

**Comment by fulcrum3d** [comment] 2015-11-26 23:46
Thank you very much, felicitus!! You really helped us. We appreciate your fast answers! :)

**Comment by felicitus** [comment] 2015-11-28 15:42
The internal part number has been added to the search filter, however, I really would like that the search field on the top right beheaves exactly like in previous versions. As this is quite a bit of effort, the final solution will be implemented in a later version.

**Comment by felicitus** [comment] 2016-07-30 18:27
I have added support for searching within name, description, internal part number and comments. Please try it out on the demo system in about one hour.

**Comment by felicitus** [comment] 2016-08-16 17:17
I believe the issue is fixed now, can you confirm?

**Comment by DoctorOctagonapus** [comment] 2016-08-24 14:28
Not OP but it's working for me.

**Closed** 2016-09-23 12:35 UTC
Labels: Feedback Needed
