### ISSUE TITLE
Multiple Locations for One Part

### ISSUE THREAD

**Issue by squintz** [partkeepr/PartKeepr#680] opened 2016-06-26 04:11 UTC
Feature Request:

If I have 1000 parts split in three locations (Joe's House, Bob's House, and the Assembly House) there is no way to indicate that 500 are at Joe's, 250 are at Bob's and 250 are the Assembly House. So I would like to request that multiple locations be supported where a single component would have sub levels of stock. I'm imagining a top level component which totals all the quantities. Under that top level would be sub levels with the details of the location and quantities at each location. The top level would have a + / - next to it to open or collapse the list of locations.

Currently a component can be duplicated but it's treated as two different components even if it's a duplicate. So when its added to a BOM it's added with a specific location indicated. This would lead to over purchasing since Joe and Bob both have components that could be sent to the assembly house.

**Comment by felicitus** [comment] 2016-07-02 21:22
Duplicate of #90

**Closed by felicitus** 2016-07-02 21:22 UTC
