### ISSUE TITLE
The server returned a response which we were not able to interpret (partkeepr-1.1.0)

### ISSUE THREAD

**Issue by WeisTekEng** [partkeepr/PartKeepr#748] opened 2016-11-25 20:05 UTC
Setup partkeepr in a virtual machine on a freenas server, per the wiki. I can access the server on my network with other computers but any action brings up the critical error window.

Here is the (full report tab) contents. This happens while trying to add parts, distributors etc.

Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET http://192.168.137.127:8080/api/system_notices?_dc=1480104197709

Response Status Code
==================================
401

Response
==================================

Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.13-1~dotdeb+8.1
auto_start_session: true
maxUploadSize: 2097152
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.WSSEAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true

**Comment by brads4** [comment] 2016-11-25 22:53
The clock on your VM must be precisely sync'd to your system clock.  The WSSE auth scheme has very little wiggle room for mismatched clocks, which causes loads of issues in the real world, even with time servers on.

**Comment by WeisTekEng** [comment] 2016-11-25 23:39
OK, bios clock right. I'll give that a look.

Thanks I'll let you know what happens.

**Comment by WeisTekEng** [comment] 2016-11-26 00:02
That now all matches, still doing the same thing when i click on anything. eg add distributor. running apache2.2 do i need to upgrade to 2.4?

**Comment by WeisTekEng** [comment] 2016-11-26 00:11
Ran setup again, chose HTTP auth and it works great so far. its on an internal network within another internal network anyway so I'm not worried about any one messing with it.

Thanks.

**Comment by brads4** [comment] 2016-11-26 00:17
The WSSEAuth in this program is tricky.  I had a LOT of issues when working with it.

Issues I have had: 
- total system lockout due to clocks being out of sync (before I knew what was going on)
- issues with web services failing due to response body sizes (this issue presents in the web layer as well)
- it seems basically, WSSE auth was never tested in real world situations, as a local dev environment would never present these types of bugs.

To assist speeding up my app, I use NGINX, which helps a lot.

**Comment by WeisTekEng** [comment] 2016-11-26 00:23
Thabks for the help and information.
Ya? You like it better than apache? I've never tried nginx, maybe in roll a
jail and see what it's like.

**Comment by brads4** [comment] 2016-11-26 00:26
It's super fast.  I'm not a super expert on web tech of this type, but I know a lot of people use it as a caching proxy in front of apache, as well  as standalone.   I chose standalone, because I wanted fast and simple. Partkeepr doesn't require any major complex server config, so I thought I'd try it out.  It's quite easy to deploy, and noticeably faster than apache.  I believe it uses non blocking IO and disposes of the thread/process per request model, in favor of reusable handlers, making scaling much much easier.

**Comment by WeisTekEng** [comment] 2016-11-26 00:27
Mmm I'll definitely have to try it out.

**Comment by brads4** [comment] 2016-11-26 00:29
It suites the actual real world conditions of today's internet, full of cyber attacks and greedy clients consuming indiscriminently.  it's gaining market share fast, and is already an industry standard as a fast caching solution for apache.

**Comment by robindegen** [comment] 2017-07-15 19:27
I'm also getting this error quite a lot on my setup.

**Comment by cach9** [comment] 2018-02-20 19:54
I have the same problem. can anybody help me. The error does not stop coming. Try nginx without apache and follow the problem.

GET http://inventario:8080/api/system_notices?_dc=1519155396693

Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET http://inventario:8080/api/system_notices?_dc=1519155396693

Response Status Code
==================================
0

Response
==================================


Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.27-0+deb9u1
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: false
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]

**Comment by justintconroy** [comment] 2018-03-04 19:09
I'm getting the same error right now

```
Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET http://partkeepr.conroy.in/api/system_notices?_dc=1520172355763

Response Status Code
==================================
0

Response
==================================


Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.6.0-DEV
php_version: 7.0.25-0ubuntu0.16.04.1
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: false
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.WSSEAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: [object Object]
```

I'm also sometimes getting a 401 response on requests to storage_locations. If I see that one again, I'll also post that error log.

**Comment by Drachenkaetzchen** [comment] 2018-03-04 19:11
@justintconroy as pointed out earlier in the thread, use HTTP Basic instead of WSSE.

**Comment by robindegen** [comment] 2018-07-20 21:12
Since the latest update I haven't received this error anymore, at least I haven't seen it yet

**Comment by christianlupus** [comment] 2020-01-18 15:25
As WSSE is deprecated and shall be replaced by HTTP Basic in the future, I am closing this here as oout-of-date.

**Comment by kivyhax** [comment] 2021-01-19 10:36
I am still receiving this error message after changing from WSSE to HTTP Basic.

```Critical Error

Details
==================================
The server returned a response which we were not able to interpret.

Request
==================================
GET http://NNNNNNNN/api/system_notices?_dc=1611052100222

Response Status Code
==================================
0

Response
==================================


Server Configuration
==================================
doctrine_orm_version: 2.5.4
doctrine_dbal_version: 2.5.2
doctrine_common_version: 2.5.3
php_version: 7.1.33-25+0~20210112.45+debian9~1.gbp1a89bf
auto_start_session: true
maxUploadSize: 2097152
isOctoPartAvailable: false
availableImageFormats: JPG,GIF,PNG
max_users: unlimited
authentication_provider: PartKeepr.Auth.HTTPBasicAuthenticationProvider
tip_of_the_day_uri: https://partkeepr.org/tips/%s
password_change: true
patreonStatus: 
defaultGridPresets: []
```

The only error message in partkeepr.log is:

```[2021-01-19 09:07:03] app.WARNING: Bad credentials. [] []```

This happens on all computers using the system; FireFox and Chrome.

I am using git master branch checked out on Nov 5th 2020

I cleared the cache following the auth provider configuration change, but may have missed additional required steps?

**Comment by christianlupus** [comment] 2021-02-05 17:35
OK, I will reopen this issue again.

**Comment by christianlupus** [comment] 2021-02-05 17:37
@kivyhax Just to make sure it is not just a trivial issue: The username and password are correct and set correctly (the same in the database as the ones you try to log in as)?

**Comment by kivyhax** [comment] 2021-02-08 05:15
@christianlupus as far as I am aware there are no issues with the passwords, though perhaps I am not catching your exact question? This issue occurs for all users on my installation. Logging in works fine, the error pops up "randomly", both in idle and active sessions. If I log in and leave the computer for an hour, I will return to find the above message. If I stay active, it will appear randomly and need to be closed to continue working.

**Comment by kivyhax** [comment] 2021-03-01 09:42
@christianlupus I have discovered a network issue at client site that appears to be the cause of this PartKeepr error message, likely this bug is already resolved in your end. 

The client's network straight up dies for a few seconds on (ir)regular intervals. My current theory is that the error message occurs if PartKeepr javascript makes the request while the network is down, which explains why there are lots of successful requests logged by the webserver, and the http 0 response code reported by PartKeepr.

**Comment by christianlupus** [comment] 2021-05-17 14:54
That sounds feasible. I will reclose then here.

**Closed by christianlupus** 2021-05-17 14:54 UTC
Labels: Bug
