### ISSUE TITLE
refreshing problem partkeepr 0.75

### ISSUE THREAD

**Issue by mctomaszek** [partkeepr/PartKeepr#493] opened 2015-11-23 12:00 UTC
hi

Partkeepr does not change automatically stock level in part detail window during add or remove.
Another issue is related to deleting users....it is the same problem like in previous versions

regards

**Comment by felicitus** [comment] 2015-11-23 12:05
Duplicate of #119 and #478

**Closed by felicitus** 2015-11-23 12:05 UTC
