### ISSUE TITLE
Problem sorting by ID

### ISSUE THREAD

**Issue by PGCJLEngineer** [partkeepr/PartKeepr#881] opened 2017-07-11 12:01 UTC
When clicking on the Internal ID tab to order items by ID reference an error is generated.
An error occurred
[Syntax Error] line 0, col 61: Error: Expected end of string, got 'id'

Client System Details:
Web Browser Used: Firefox 52.2.1 (32-Bit), WinXP.

Server Details
Ubuntu 16.04LTS
Linux RSLERP 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Partkeepr Version 1.1.0
Reproducible on the demo system: Yes

# How to reproduce
Click on Internal ID tab to sort items by ID reference. An error is generated.

**Comment by felicitus** [comment] 2017-07-11 12:11
Duplicate of #827

**Closed by felicitus** 2017-07-11 12:11 UTC
