### ISSUE TITLE
Partkeepr 1.0 doesn't search Description field anymore

### ISSUE THREAD

**Issue by backstube** [partkeepr/PartKeepr#694] opened 2016-07-28 16:26 UTC
Hi,
in my previous install, 0.1.9, PK did search substrings in Description and Comment fields of every part record in database, and Name field of course.

Now on 1.0, search in Name is still there, but Description and Comment are gone. This was very useful before! Why's that? Must be a bug.

I, for one, want that back, because a lot of descriptive text is stored in those fields and thus shall be searchable in order to find those parts. It would be a huge amount of work to move and cram all of this relevant date into Name field alone just to have it within the scope of search function.

**Comment by agardim** [comment] 2016-07-29 13:38
I need it too and already asked this feature back.

**Comment by backstube** [comment] 2016-07-29 19:22
Yes, I've read your issue #691 before writing this one. Wrote this new one for pointing out that v1.0 omitting more fields than just one field as in your issue. Wanted to cross reference, but forgot in the end. Sorry for that, agardim. And thanks for commenting here.

**Comment by backstube** [comment] 2016-07-30 11:07
In terms of search, PK v1.0 is way worse than v0.1.9 was before. Not only it doesn't query the beforementioned fields to find parts, it also misses have-to matches in the Name field.

Moreover, this doesn't seem to be always the case. Sometimes parts are being found on a given search string, some are not. 

I became aware of this when directly navigating to parts, in other words doing a category browse to that part, and then query that part by words in it's Name field resulting in a no-match. Bummer.

**Comment by felicitus** [comment] 2016-07-30 12:09
This is a duplicate of #501 

@backstube can you reproduce the problem you are mentioning in your last comment? If so, please open a new issue, preferably with instructions on how to reproduce.

**Closed by felicitus** 2016-07-30 12:09 UTC

**Comment by backstube** [comment] 2016-07-30 12:24
Well, I am not entirely sure that this one is a dupe of #501 which is about internal part numbers (initially). 

Also, it covers long gone PK milestones. This one is about PK v1.0 and search function not being able to barely find anything anymore. Very frustrating to be locked-in to a system that worked before (search-wise) pretty good, now having lost approx. 80 % usefulness in an upgrade (with the hopes to improve things).

**Comment by felicitus** [comment] 2016-07-30 12:25
Yes, I agree. I will see if I can fix it it soon.

**Comment by backstube** [comment] 2016-07-30 16:42
> Yes, I agree. I will see if I can fix it it soon.

Thanks, that'll be great.

**Comment by felicitus** [comment] 2016-07-30 18:29
I just added a commit which hopefully fixes the issue, you can try it on the demo system in about one hour.

**Comment by backstube** [comment] 2016-08-01 13:26
Hi,
thanks for the swift reaction time.

Since you said no word reg. change(s) you made and their intended effect(s) on search, the following is what I've found. All tests happended on demo.partkeepr.org. 

a.) search now does find strings in Description and Comment fields, which is good. However, if a part is needed that happens to be a MOSFET by International Rectifier w/ 29 Amps, I would enter "IRFZ 29A". Result: no match. It's there, but IRFZ is in Name, whereas 29A is in Description field.

b.) there's an "LED, 5x2,5mm, rot". A query for "LED rot" results in zero matches. There also is a part named "LED Mix". A query for those two words does find that part. Why's that? 
This behaviour I also have found in our v1.0 installation and reported that as search being inconsistent.

c.) a search with substring "BC" does match with all parts (mainly Si-Transistors) that have it in either Name or Description or Comment field. But only as long as there comes no other word along in search query like "BC 45V". This is pretty much related to a.) except for the fraction-of-a-word part.

d.) search doesn't find and list all parts which have words in Comment in the boolean OR sense: There are 3 parts: BC547A, BC547B, BC547C. In Comment field, they have alice, bob, claire, respectively. So a query "alice bob claire" OR-ed them in PK v0.1.9, thus spit out all three parts associated to them. In PK v1.0: zero matches.

In my opinion v1.0 search is no better in any conceivable way in comparison to v0.1.9 search back in the day. So if I could chose I'd clearly make it like it was before. I cannot remember any flaws it had then.

**Comment by felicitus** [comment] 2016-08-01 13:31
@backstube can you put this into the other issue? As the issue is closed, I could easily miss it

**Comment by backstube** [comment] 2016-08-01 16:43
Sure. Check.
