### ISSUE TITLE
Can't properly move multiple parts

### ISSUE THREAD

**Issue by riain43** [partkeepr/PartKeepr#663] opened 2016-05-12 02:12 UTC
I've noticed that when I try to highlight multiple parts, then move them from one Category to another, the interface shows that it's registered multiple items to be moved, but on releasing the mouse, only one item gets transferred.

**Comment by felicitus** [comment] 2016-05-14 14:45
I believe the issue is now fixed. Can you try on the demo system in about one hour to confirm that it's fixed?

**Closed** 2016-05-14 14:45 UTC

**Comment by riain43** [comment] 2016-05-15 03:24
Thanks for that, it seems to be working on demo site. I'll paste the new code into my installation and test there, too.
