### ISSUE TITLE
Part detail picture auto scale

### ISSUE THREAD

**Issue by hebere** [partkeepr/PartKeepr#277] opened 2013-01-21 08:59 UTC
Pictures of Parts does not scale well. We will upload pictures with url from distributors web pages. 

So auto scale is important for us.

![autoscale](https://f.cloud.github.com/assets/3327077/82435/3877e534-63a8-11e2-8680-b1cf264b016e.jpg)
![poor_resolution](https://f.cloud.github.com/assets/3327077/82440/82db3f7c-63a8-11e2-9ed2-48d2cc6f898f.png)

**Comment by felicitus** [comment] 2016-04-28 12:15
I believe the issue is now fixed. Small pictures don't get scaled up anymore:
![image](https://cloud.githubusercontent.com/assets/162974/14885425/967770be-0d4b-11e6-86dc-91e1b8158dd6.png)

**Closed by felicitus** 2016-04-28 12:15 UTC
Labels: Bug
