### ISSUE TITLE
Storage location hierachy

### ISSUE THREAD

**Issue by HKay** [partkeepr/PartKeepr#388] opened 2015-02-11 18:00 UTC
It would be nice to be able to create sub-locations in storage locations.
This is very useful for drawers and sorting boxes with many small trays. Those could be identified with an X/Y position within a storage location.
[Shelf number] -> [Box number] -> [X/Y position]

**Comment by felicitus** [comment] 2015-06-20 20:23
Duplicate of #225

**Closed by felicitus** 2015-06-20 20:23 UTC
