### ISSUE TITLE
Problems using "Create blank item after save"

### ISSUE THREAD

**Issue by MrTinkerman** [partkeepr/PartKeepr#571] opened 2016-01-17 19:46 UTC
Hi,

==PK 0.76 on Raspberry Pi2==

I was using the option "Create blank item after save", **after the first save**:
- The save button is greyed out, only after a while it activates but sometimes it does not activate at all, sometimes it activates on mouseover, sometimes it activates after clicking around or editing input.
- The tabs Distributors, Manufacturers, Parameters, Attachments are blank.
- The "Add Part" window disappears when dragging it.

I tested in Firefox, Chrome and IE on windows and also Firefox, Chrome and Safari on my Macbook Air

In Firefox and Chrome this happens too (on both Win and Mac): 

![chrome_bug](https://cloud.githubusercontent.com/assets/16565076/12379415/7cc2bdfe-bd5a-11e5-8b69-9c5c7642c120.jpg)

![firefox_bug](https://cloud.githubusercontent.com/assets/16565076/12379419/8274097e-bd5a-11e5-894e-f0176d9fb45a.jpg)

Can you confirm/reproduce this error ?

**Comment by felicitus** [comment] 2016-02-23 14:46
I can't reproduce it. Can you have a look at your JavaScript console if there are any errors? On most browsers you can open the console by pressing F12.

**Comment by felicitus** [comment] 2016-05-14 14:54
No feedback given for an extended period of time, closing the issue.

Feel free to re-open if you have additional information.

**Closed by felicitus** 2016-05-14 14:54 UTC
Labels: Feedback Needed
